Repository sampadatiwari30/kala.ficial, pull requests merged in 2025-09, with the labels that each got.

#47 Mobile Responsive UI
  Artist Portal.html
  artwork.html
  auth.html
  blog.css
  exhibition.html
  index.html
Labels: enhancement, gssoc25

#49 Added new responsive footer
  exhibition.html
  index.html
Labels: enhancement, gssoc25

#90 first
  artwork.html
  index.html
Labels: bug, gssoc25

#93 ADD about us Page
  about.html
  index.html
  kala.png
Labels: enhancement, gssoc25

#94 ADD Contact Us Page
  contact.html
Labels: enhancement, gssoc25

#91 update artwork page in same theme
  Painting5.jpeg
  artwork.html
  painting.jpeg
  painting1.webp
  painting2.webp
  painting3.webp
  painting4.webp
  painting6.webp
Labels: enhancement, gssoc25

#114 navigation fixed
  about.html
Labels: bug, gssoc25

#110 Add scroll-to-top/bottom button across all pages
  Artist Portal.html
  about.html
  artwork.html
  contact.html
  exhibition.html
  index.html
Labels: enhancement, gssoc25

#122 Add back to top redirection in readme.md
  README.md
Labels: documentation, gssoc25

#128 Add theme-toggle.js for universal theme switching functionality
  theme-toggle.js
Labels: enhancement, gssoc25

#129 Made the site Logo Clickable
  .vscode/settings.json
  about.html
  artwork.html
  exhibition.html
  index.html
  theme-test.html
  theme-toggle.js
Labels: enhancement, gssoc25

#151 added logout confirmation logout modal
  about.html
  artwork.html
  exhibition.html
  index.html
Labels: enhancement, gssoc25

#153 Make Login & Signup pages scrollable and responsive across devices
  Components/css/auth.css
  auth.html
Labels: bug, gssoc25

#166 Adding a loader animation
  index.html
Labels: enhancement, gssoc25

#180 Adding a FAQ page
  faq.html
  index.html
Labels: enhancement, gssoc25
